### ISSUE TITLE
How create workflow when the argo server don't need token?

### ISSUE THREAD

**Issue by MichaelLan** [argoproj-labs/hera-workflows#239]
I tried create a workflow with token in None but the get_global_token function crash me.

My code. 
```python
from hera import Task, Workflow, WorkflowService

from config import HOST

with Workflow("container", service=WorkflowService(host=HOST, token=None, verify_ssl=False)) as w:
    Task("cowsay", image="docker/whalesay", command=["cowsay", "foo"])

w.create()
```

Code error
```bash
Traceback (most recent call last):
  File "/home/michaellan/Development/tickets-mesh/src/main.py", line 7, in <module>
    with Workflow("container", service=WorkflowService(host=HOST, verify_ssl=False)) as w:
  File "/home/michaellan/.cache/pypoetry/virtualenvs/tickets-mesh-nDdbz3ZY-py3.9/lib/python3.9/site-packages/hera/workflow_service.py", line 45, in __init__
    api_client = Client(self._config, token=token).api_client
  File "/home/michaellan/.cache/pypoetry/virtualenvs/tickets-mesh-nDdbz3ZY-py3.9/lib/python3.9/site-packages/hera/client.py", line 33, in __init__
    assert token, "No token was provided and no global token was found."
AssertionError: No token was provided and no global token was found.
```

**Comment by MichaelLan** [comment]
Sorry, only sending token with an empty string is sufficient.
