### ISSUE TITLE
SSL Certifciate

### ISSUE THREAD

**Issue by alejoGT1202** [argoproj-labs/hera-workflows#384]
Hello,

I'm trying to submit this [example workflow ](https://github.com/argoproj-labs/hera-workflows/blob/main/examples/diamond.py). I've set `hera.set_global_token` and `hera.set_global_host` as specified on the comments. However I'm getting an error related to `SSL` certificates. Is there a way I can disable the verification from the certificate?

Thanks for the help, 

```
Traceback (most recent call last):
  File "/home/alejo/Documents/Nodes/Nodes/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/alejo/Documents/Nodes/Nodes/lib/python3.8/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/home/alejo/Documents/Nodes/Nodes/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/home/alejo/Documents/Nodes/Nodes/lib/python3.8/site-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/home/alejo/Documents/Nodes/Nodes/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/home/alejo/Documents/Nodes/Nodes/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 23, in <module>
    w.create()
  File "/home/alejo/Documents/Nodes/Nodes/lib/python3.8/site-packages/hera/workflow.py", line 312, in create
    resulting_argo_wf = self.service.create_workflow(self.build())
  File "/home/alejo/Documents/Nodes/Nodes/lib/python3.8/site-packages/hera/workflow_service.py", line 81, in create_workflow
    return WorkflowServiceApi(api_client=self._api_client).create_workflow(
  File "/home/alejo/Documents/Nodes/Nodes/lib/python3.8/site-packages/argo_workflows/api_client.py", line 771, in __call__
    return self.callable(self, *args, **kwargs)
  File "/home/alejo/Documents/Nodes/Nodes/lib/python3.8/site-packages/argo_workflows/api/workflow_service_api.py", line 121, in __create_workflow
    return self.call_with_http_info(**kwargs)
  File "/home/alejo/Documents/Nodes/Nodes/lib/python3.8/site-packages/argo_workflows/api_client.py", line 833, in call_with_http_info
    return self.api_client.call_api(
  File "/home/alejo/Documents/Nodes/Nodes/lib/python3.8/site-packages/argo_workflows/api_client.py", line 408, in call_api
    return self.__call_api(resource_path, method,
  File "/home/alejo/Documents/Nodes/Nodes/lib/python3.8/site-packages/argo_workflows/api_client.py", line 195, in __call_api
    response_data = self.request(
  File "/home/alejo/Documents/Nodes/Nodes/lib/python3.8/site-packages/argo_workflows/api_client.py", line 454, in request
    return self.rest_client.POST(url,
  File "/home/alejo/Documents/Nodes/Nodes/lib/python3.8/site-packages/argo_workflows/rest.py", line 266, in POST
    return self.request("POST", url,
  File "/home/alejo/Documents/Nodes/Nodes/lib/python3.8/site-packages/argo_workflows/rest.py", line 152, in request
    r = self.pool_manager.request(
  File "/home/alejo/Documents/Nodes/Nodes/lib/python3.8/site-packages/urllib3/request.py", line 78, in request
    return self.request_encode_body(
  File "/home/alejo/Documents/Nodes/Nodes/lib/python3.8/site-packages/urllib3/request.py", line 170, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/home/alejo/Documents/Nodes/Nodes/lib/python3.8/site-packages/urllib3/poolmanager.py", line 376, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/alejo/Documents/Nodes/Nodes/lib/python3.8/site-packages/urllib3/connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "/home/alejo/Documents/Nodes/Nodes/lib/python3.8/site-packages/urllib3/connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "/home/alejo/Documents/Nodes/Nodes/lib/python3.8/site-packages/urllib3/connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "/home/alejo/Documents/Nodes/Nodes/lib/python3.8/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/home/alejo/Documents/Nodes/Nodes/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='localhost', port=2746): Max retries exceeded with url: //api/v1/workflows/default (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))
```

**Comment by flaviuvadan** [comment]
Thank you for the question @alejoGT1202! There's a `verify_ssl` field that is accessible on [GlobalConfig](https://github.com/argoproj-labs/hera-workflows/blob/main/src/hera/global_config.py#L43)

**Comment by flaviuvadan** [comment]
@alejoGT1202 closing this as the `GlobalConfig.verify_ssl` flag is designed for this! Of course, please feel free to reopen the issue! :)

**Comment by alejoGT1202** [comment]
Hello @flaviuvadan 

Thanks for the help I was able to disable the SSL certificate. However, I'm getting the following errors:

If a stables my host as `set_global_host('https://localhost:2746/')` and try to submit something I get the following error:

```
argo_workflows.exceptions.UnauthorizedException: (401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'Trailer': 'Grpc-Trailer-Content-Type', 'Date': 'Wed, 14 Dec 2022 13:06:52 GMT', 'Transfer-Encoding': 'chunked'})
HTTP response body: {"code":16,"message":"Unauthorized"}
```

When I set the host as `set_global_host('http://localhost:2746/')` and try to submit something I get the following error:

  ```
  raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

I'm passsing the Bearer Token at  `set_global_token`() as `set_global_token('Bearer <MY_TOKEN>')`

Is there a configuration that I'm missing?

**Comment by flaviuvadan** [comment]
I wonder if this is related to [this issue](https://github.com/argoproj-labs/hera-workflows/issues/394). Any chance you can try the suggested flags?

**Comment by BnJam** [comment]
These were the same error messages I was getting until I figured out #394 - should fix this problem.

**Comment by flaviuvadan** [comment]
Closing this as #394 was deployed. Free free to reply here and we can reopen the issue for discussion if it persists! :)
