### ISSUE TITLE
AttributeError: 'SecretEnv' object has no attribute '__fields_set__'

### ISSUE THREAD

**Issue by menzenski** [argoproj-labs/hera-workflows#502]
I am trying to upgrade from hera-workflows 4.4.1 to latest 5.0.0rc2.

In 4.4.1, I can define a secret with SecretEnv this way:

```python
            SecretEnv(
                name="SECRET_ENV_VAR_NAME", secret_name="my-secret", secret_key="my-key"
            ),
```

I've tried to do the same with the latest version but am getting an error.

Here's a full python file:

```python
from hera.workflows import ConfigMapEnv, ConfigMapEnvFrom, SecretEnv,WorkflowTemplate, Container, Steps, Step

with WorkflowTemplate(
    name="my-workflow-template",
) as wt:
    my_container = Container(
        name="my-container",
        image="my-org/my-repo:latest",
        command=["my-command"],
        env=[
            SecretEnv(
                name="SECRET_ENV_VAR_NAME", secret_name="my-secret", secret_key="my-key"
            ),
            ConfigMapEnv(
                name="CONFIG_MAP_ENV_VAR_NAME", config_map_name="my-config-map", config_map_key="my-key"
            ),
        ],
        env_from=[
            ConfigMapEnvFrom("my-config-map"),
        ]
    )

    with Steps(name="my-steps") as s:

        Step(
            name="my-step",
            template="my-container"
        )


if __name__ == "__main__":
    print(wt.to_yaml())
```

Our process thus far has been to manually create the YAML from the hera-workflows Python by executing the Python script and directing its output to a YAML file. For instance, `python test.py > test.yaml` (and then we manage the YAML with ArgoCD).

When I try to execute this python script, I get this error: 

```
Traceback (most recent call last):
  File "/Users/matt/dev/paw_elt/argo/src/test.py", line 11, in <module>
    SecretEnv(
  File "/Users/matt/dev/paw_elt/argo/__pypackages__/3.11/lib/hera/workflows/env.py", line 88, in __init__
    self.secret_key = secret_key
    ^^^^^^^^^^^^^^^
  File "pydantic/main.py", line 405, in pydantic.main.BaseModel.__setattr__
AttributeError: 'SecretEnv' object has no attribute '__fields_set__'
```

**Comment by shuvozula** [comment]
I am getting the same error, but with just `Env`, which is similar to SecretEnv as they both inherit from _BaseEnv
